### ISSUE TITLE
Does not work with deno 1.0.2

### ISSUE THREAD

**Issue by mushtaq** [zhmushan/dev_server#2]
When I do `deno install -A --unstable https://deno.land/x/dev_server/mod.ts`, 
I get the following error:

```txt
Download https://deno.land/x/dev_server/mod.ts
Download https://deno.land/x/dev_server/types.ts
Download https://deno.land/x/dev_server/deps.ts
Download https://deno.land/x/abc@v1.0.0-rc4/mod.ts
Download https://deno.land/x/abc@v1.0.0-rc4/middleware/logger.ts
Download https://deno.land/x/abc@v1.0.0-rc4/constants.ts
Download https://deno.land/std@0.51.0/path/mod.ts
Download https://deno.land/std@0.51.0/fs/mod.ts
Download https://deno.land/std@0.51.0/flags/mod.ts
Download https://deno.land/std@0.51.0/fmt/colors.ts
Download https://deno.land/x/abc@v1.0.0-rc4/types.ts
Download https://deno.land/x/abc@v1.0.0-rc4/context.ts
Download https://deno.land/x/abc@v1.0.0-rc4/middleware/skipper.ts
Download https://deno.land/std@0.51.0/path/win32.ts
Download https://deno.land/std@0.51.0/path/posix.ts
Download https://deno.land/std@0.51.0/path/common.ts
Download https://deno.land/std@0.51.0/path/separator.ts
Download https://deno.land/std@0.51.0/path/interface.ts
Download https://deno.land/std@0.51.0/path/glob.ts
Download https://deno.land/std@0.51.0/fs/empty_dir.ts
Download https://deno.land/std@0.51.0/fs/ensure_dir.ts
Download https://deno.land/std@0.51.0/fs/ensure_file.ts
Download https://deno.land/std@0.51.0/fs/ensure_link.ts
Download https://deno.land/std@0.51.0/fs/ensure_symlink.ts
Download https://deno.land/std@0.51.0/fs/exists.ts
Download https://deno.land/std@0.51.0/fs/expand_glob.ts
Download https://deno.land/std@0.51.0/fs/move.ts
Download https://deno.land/std@0.51.0/fs/copy.ts
Download https://deno.land/std@0.51.0/fs/read_file_str.ts
Download https://deno.land/std@0.51.0/fs/write_file_str.ts
Download https://deno.land/std@0.51.0/fs/read_json.ts
Download https://deno.land/std@0.51.0/fs/write_json.ts
Download https://deno.land/std@0.51.0/fs/walk.ts
Download https://deno.land/std@0.51.0/fs/eol.ts
Download https://deno.land/std@0.51.0/testing/asserts.ts
Download https://deno.land/x/abc@v1.0.0-rc4/app.ts
Download https://deno.land/x/abc@v1.0.0-rc4/group.ts
Download https://deno.land/x/abc@v1.0.0-rc4/router.ts
Download https://deno.land/x/abc@v1.0.0-rc4/node.ts
Download https://deno.land/x/abc@v1.0.0-rc4/http_exception.ts
Download https://deno.land/x/abc@v1.0.0-rc4/deps.ts
Download https://deno.land/x/abc@v1.0.0-rc4/util.ts
Download https://deno.land/std@0.51.0/path/_globrex.ts
Download https://deno.land/std@0.51.0/path/_constants.ts
Download https://deno.land/std@0.51.0/path/_util.ts
Download https://deno.land/std@0.51.0/fs/_util.ts
Download https://deno.land/std@0.51.0/testing/diff.ts
Download https://deno.land/std@0.51.0/http/cookie.ts
Download https://deno.land/std@0.51.0/http/server.ts
Download https://deno.land/std@0.51.0/http/http_status.ts
Download https://deno.land/std@0.51.0/encoding/utf8.ts
Download https://deno.land/std@0.51.0/mime/multipart.ts
Download https://deno.land/std@0.51.0/datetime/mod.ts
Download https://deno.land/std@0.51.0/io/bufio.ts
Download https://deno.land/std@0.51.0/async/mod.ts
Download https://deno.land/std@0.51.0/http/_io.ts
Download https://deno.land/std@0.51.0/bytes/mod.ts
Download https://deno.land/std@0.51.0/io/ioutil.ts
Download https://deno.land/std@0.51.0/io/readers.ts
Download https://deno.land/std@0.51.0/io/util.ts
Download https://deno.land/std@0.51.0/textproto/mod.ts
Download https://deno.land/std@0.51.0/_util/has_own_property.ts
Download https://deno.land/std@0.51.0/async/deferred.ts
Download https://deno.land/std@0.51.0/async/delay.ts
Download https://deno.land/std@0.51.0/async/mux_async_iterator.ts
Compile https://deno.land/x/dev_server/mod.ts
error: TS2345 [ERROR]: Argument of type '"file" | "dir" | "symlink" | undefined' is not assignable to parameter of type 'SymlinkOptions | undefined'.
  Type '"file"' is not assignable to type 'SymlinkOptions | undefined'.
  await Deno.symlink(originSrcFilePath, dest, type);
                                              ~~~~
    at https://deno.land/std@0.51.0/fs/copy.ts:114:47

TS2345 [ERROR]: Argument of type '"file" | "dir" | "symlink" | undefined' is not assignable to parameter of type 'SymlinkOptions | undefined'.
  Type '"file"' is not assignable to type 'SymlinkOptions | undefined'.
  Deno.symlinkSync(originSrcFilePath, dest, type);
                                            ~~~~
    at https://deno.land/std@0.51.0/fs/copy.ts:132:45

TS2345 [ERROR]: Argument of type '"file" | "dir" | "symlink" | undefined' is not assignable to parameter of type 'SymlinkOptions | undefined'.
  Type '"file"' is not assignable to type 'SymlinkOptions | undefined'.
  await Deno.symlink(src, dest, srcFilePathType);
                                ~~~~~~~~~~~~~~~
    at https://deno.land/std@0.51.0/fs/ensure_symlink.ts:31:33

TS2345 [ERROR]: Argument of type '"file" | "dir" | "symlink" | undefined' is not assignable to parameter of type 'SymlinkOptions | undefined'.
  Type '"file"' is not assignable to type 'SymlinkOptions | undefined'.
  Deno.symlinkSync(src, dest, srcFilePathType);
                              ~~~~~~~~~~~~~~~
    at https://deno.land/std@0.51.0/fs/ensure_symlink.ts:58:31

Found 4 errors.
```

**Comment by zhmushan** [comment]
@mushtaq Fixed in https://github.com/zhmushan/dev_server/commit/43b17f236241203c2f086c0318cde733a6b60341
